// serviceWorkerRegistration.ts
// Registers the PWA service worker generated by vite-plugin-pwa.
// This is imported once at application startup.

import { registerSW } from 'virtual:pwa-register'

// `registerSW` returns a function to manually trigger an update.
// We call it so that the service worker is registered immediately
// and then check periodically for updates so users get the freshest build.

export const registerServiceWorker = () => {
  // `registerSW` accepts options. Here we opt into periodic checks.
  registerSW({
    immediate: true,
    onRegistered(r) {
      console.log('Service worker registered', r)
    },
    onRegisterError(error) {
      console.error('Service worker registration failed', error)
    },
  })
}
