/// <reference types="vite/client" />

// Add type declaration for the PWA virtual module generated by vite-plugin-pwa
// so that TypeScript does not complain in the web build.
declare module 'virtual:pwa-register' {
  export interface RegisterSWOptions {
    immediate?: boolean
    onRegistered?: (registration?: ServiceWorkerRegistration | undefined) => void
    onRegisterError?: (error: any) => void
    onNeedRefresh?: () => void
    onOfflineReady?: () => void
  }
  export function registerSW(options?: RegisterSWOptions): (reloadPage?: boolean) => void
}
